
name: CI for py

on: [push, pull_request]

jobs:
# applying the ci workflow to out repository and checking all the linters that we have
  python-lint:
    runs-on: ubuntu-latest
    steps:
# actions/checkout@v2 do simply checks out the code from the repo so we can run associated actions later on as well
      - name: checkout source repo
        uses: actions/checkout@v2

# github action we're going to be using is  alexanderdamiani/pylinter@v1.0.0  (pylinter)
      - name: linting
        uses: alexanderdamiani/pylinter@v1.0.0
        with:
          python-root: '.'
          flake8-flags: ''
          mypy-flags: ''
          fail-on-isort: false
  
  #flake8, mypy, they'are a little too complex to apply changes automatically but isrot is much mor simplistic all its doing is sorting the imports alphabetically automatically
  
  # auto commit and auto push of changes made by our ci workflow to the repository when it encounters work changes that need to be made
  #isort is doing is simply sorting the imports of the repository in alphabetical order
  
      - name: commit isort changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A && git diff-index --cached --quiet HEAD || git commit -m 'isort'
          
      - name: push isort changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          #secret code github /underscore accees /underscore token to the repo https://docs.github.com/es/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

          github_token: ${{ secrets.GH_ACCES_TOKE }}
          branch: ${{ github.ref }}
